### ISSUE TITLE
Plugin doesn't work after the last RustAutoComplete.py modification

### ISSUE THREAD

**Issue by denis631** [glennw/RustAutoComplete#21]
I've tried to download the latest RustAutoComplete plugin from github with modified RustAutoComplete.py file, which enables better autocompletion, but the autocompletion just doesn't work. 
But when I put the old plugin, everything works fine.

Is it only by me, or is there anyone with the same problem ?

**Comment by glennw** [comment]
Did you also update the racer executable?

**Comment by denis631** [comment]
Didn't do that, I thought I is not necessary.
Everything works fine now! Thanks
