### ISSUE TITLE
It's not an issue, but a request.

### ISSUE THREAD

**Issue by denis631** [glennw/RustAutoComplete#6]
I've only started today with Rust, so If I'm wrong, or my code is wrong, don't judge me :)
As I understood my autocompletion works
![screenshot from 2014-10-05 15 42 43](https://cloud.githubusercontent.com/assets/6100421/4518686/63b3ec1c-4c99-11e4-9bb6-e3abcd520904.png)

Still something is wrong (or maybe rust is updating too quickly :) ), cause when I try to test the code you've written no suggestions are shown (like new, with_hasher etc.)
![screenshot from 2014-10-05 15 44 11](https://cloud.githubusercontent.com/assets/6100421/4518687/63b4477a-4c99-11e4-9bec-0d8d8944a81a.png)

What I find cool, is that it also searches your current file for autocompletion. That's awesome.
It would be great, if autocompletion could show the return type of the function. I'm sure it's a good feature.
![screenshot from 2014-10-05 15 56 53](https://cloud.githubusercontent.com/assets/6100421/4518688/63ba6c2c-4c99-11e4-877d-32b0fdf60574.png)

No autocompletion for println, or stuff like to_string etc.
![screenshot from 2014-10-05 16 22 49](https://cloud.githubusercontent.com/assets/6100421/4518730/32dd48fc-4c9b-11e4-9bf2-4041712e77f5.png)
![screenshot from 2014-10-05 16 23 00](https://cloud.githubusercontent.com/assets/6100421/4518729/32dd08f6-4c9b-11e4-8b9e-cf5a27230538.png)

P.S. I didn't want to write it in Issue section, but I couldn't find your mail. Thanks in advance.

**Comment by denis631** [comment]
Will the RustAutoComplete plugin for sublime get this feature, which the author of the racer, wrote in his blog about half a year ago ?
http://phildawes.net/blog/
![racer4](https://cloud.githubusercontent.com/assets/6100421/5672394/5da07358-9790-11e4-8d29-81acb9dfaed0.png)

**Comment by glennw** [comment]
I don't have time to work on it actively at the moment - PRs are always welcome of course :) I may get some time in the next few months to work on it again.
